### ISSUE TITLE
Release v1.3: make compile fails with 'bin/lfeexec': No such file or directory

### ISSUE THREAD

**Issue by starkertyp** [lfe/lfe#342]
Hi,
I currently try to get the lfe package in gentoo to a more up to date state and tried to compile from the v1.3 tag for that. Make compile currently fails at trying to install lfeexec  [(example build log for that)](https://github.com/rvirding/lfe/files/1059229/build.txt)
This issue seems to be fixed on the develop branch so this isn't that big of a deal for actual usage but it makes packaging a bit difficult and might seem weird for users just wanting the latest release build.

Thanks for all the hard work!

**Comment by yurrriq** [comment]
Can you confirm whether the develop branch works o Gentoo? 1.3.1 should be coming soon and will include the Makefile fix and one for a tricky let/guard/record issue.

**Comment by yurrriq** [comment]
I'm looking to do some packaging work too, once 1.3.1 is released. Check out #341. Is there anything else we're missing?

**Comment by starkertyp** [comment]
I made a few more tests from the current develop branch, head is at b8f3e06 right now.
- make compile runs fine
- rebar3 eunit passes without failures
- (progn (include-lib "lfe/include/clj.lfe") (-> 2 (+ 2))) returns 4 as mentioned in #341 
- I am able to compile and run the examples (well, at least the ones i tested...)

make install, however, fails for me at the install-beam target. Running **make install PREFIX=/tmp** fails with the following error:
``
install: will not overwrite just-created '/tmp/lib/lfe/ebin/lfe_scan.beam' with 'ebin/lfe_scan.beam'
``
(full log at: [make_install.txt](https://github.com/rvirding/lfe/files/1062261/make_install.txt))

The problem seems to be that EBINS contains lfe_scan.beam twice, which can be seen when running make echo. Maybe this happens because there is a lfe_scan.erl and a lfe_scan.xrl and both of them result in a beam file of the same name?

**Comment by starkertyp** [comment]
Not sure if this helps but I just checked the result of make echo on the v1.2.1 tag and that version doesn't seem to have that issue.

make echo | grep lfe_scan.beam on v1.2.1:
`
lfe_shell.beam lfe_io_pretty.beam lfe_macro.beam lfe_io_write.beam lfe_lint.beam lfe_doc.beam lfe_io_format.beam lfe_comp.beam lfe_env.beam lfe_pmod.beam lf
e_macro_include.beam lfe_codegen.beam lfe_macro_record.beam lfescript.beam lfe_parse.beam lfe_edlin_expand.beam lfe_bits.beam lfe_lib.beam lfe_macro_export.
beam lfe_gen.beam lfe_io.beam lfe_qlc.beam lfe_trans.beam lfe_ms.beam lfe_init.beam lfe_eval.beam lfe.beam lfe_scan.beam
`

make echo | grep lfe_scan.beam on develop:
`
lfe_shell.beam lfe_io_pretty.beam lfe_macro.beam lfe_io_write.beam lfe_types.beam lfe_lint.beam lfe_doc.beam lfe_io_format.beam lfe_comp.beam lfe_env.beam lfe_scan.beam lfe_internal.beam lfe_pmod.beam
lfe_macro_include.beam lfe_codegen.beam lfe_macro_record.beam lfescript.beam lfe_parse.beam lfe_edlin_expand.beam lfe_bits.beam lfe_lib.beam lfe_macro_export.beam lfe_gen.beam lfe_io.beam lfe_qlc.beam
lfe_trans.beam lfe_ms.beam lfe_init.beam lfe_eval.beam lfe.beam lfe_scan.beam
`

This might not be a big deal for packaging in gentoo, the current package basically just copies the .beam files inside the ebin directory to /usr/lib/erlang/lib/lfe/ebin and I could just do the same for v1.3.1 when it arrives.

**Comment by dinapappor** [comment]
Trying to update the FreeBSD port of lfe. And I am suffering the same problem. Is there a fix for this problem? This is with 1.3.

**Comment by yurrriq** [comment]
I think maybe @oubiwann has a fix for this somewhere...

**Comment by molnarp** [comment]
I am having the same problem with both v1.3 and master on Fedora 26.
```
$ make compile
[...]
erlc -I include -o ebin -DERLANG_VERSION=\"19.3.6.2\" -DHAS_MAPS=true -DHAS_FULL_KEYS=true -DNEW_REC_CORE=true -DNEW_RAND=true -W1 src/lfe_scan.erl
install -m755 bin/lfeexec /usr/local/lib/lfe/bin
install: cannot stat 'bin/lfeexec': No such file or directory
make[1]: *** [Makefile:121: bin/lfeexec] Error 1
```

**Comment by Viddi** [comment]
Btw this has been fixed on the develop branch. I built the project on develop and it installed fine for me on Arch.

@rvirding Is there any way to make a version 1.3.1 release to fix this issue? If the next release is a few weeks out still.

**Comment by OvermindDL1** [comment]
Still the same issue, v1.3 will still not compile, no v1.3.1 found.

**Comment by fhunleth** [comment]
I just ran into this too. Could a 1.3.1 release be made?

**Comment by oubiwann** [comment]
We're preparing for an LFE 2.0 release -- almost there!

(The fixes that were in 1.3-dev will be in 2.0.)

**Comment by oubiwann** [comment]
I'm going to close this ticket, as the fixes have been in place for a while now.
