### ISSUE TITLE
Pattern matching of binary argument works in REPL but does not compile

### ISSUE THREAD

**Issue by dendrown** [lfe/lfe#430]
Hello.  I am having a problem pattern matching to a binary function argument in LFE.  This works fine in the REPL:
```lfe
lfe> (defun chop
lfe>   (((binary "xyz" (more binary)))
lfe>     (io:format "CHOP: ~p~n" `(,more)))
lfe> 
lfe>   ((-)
lfe>     'nochop))
chop
lfe> (chop #"hello")
nochop
lfe> (chop #"xyzhello")
CHOP: <<"hello">>
ok
```
However, when I have the exact same function in a source module:
```lfe
(defmodule afterxyz
  (export (chop 1)))


(defun chop
  (((binary "xyz" (more binary)))
    (io:format "CHOP: ~p~n" `(,more)))

  ((-)
    'nochop))
```
...and try to compile it:
```lfe
lfe> (c 'afterxyz)
#(error
  #(#(badmatch
      #(#(bin_element 5 #(string 5 "xyz") default default) #(to () #M() () ())))
    (#(lfe_translate mapfoldl3 5
       (#(file "src/lfe_translate.erl") #(line 1268)))
     #(lfe_translate to_pat 5 (#(file "src/lfe_translate.erl") #(line 1160)))
     #(lfe_translate mapfoldl3 5
       (#(file "src/lfe_translate.erl") #(line 1268)))
     #(lfe_translate to_pats 4 (#(file "src/lfe_translate.erl") #(line 1181)))
     #(lfe_translate to_fun_cl 4
       (#(file "src/lfe_translate.erl") #(line 928)))
     #(lists mapfoldl 3 (#(file "lists.erl") #(line 1358)))
     #(lfe_translate to_expr 4 (#(file "src/lfe_translate.erl") #(line 701)))
     #(lfe_translate to_expr 3 (#(file "src/lfe_translate.erl") #(line 593))))))
```
The is using LFE 2.0 (1feb8af64c977946b6184b7d63b436c49dbeb52d) on Erlang/OTP 23 [erts-11.2].  I created the sample code based on a larger project where compiling a module with a function trying to pattern match a binary argument in a similar way.  It crashes on `rebar3 lfe compile`, and the `rebar3.crashdump` contains essentially the same error.  Compiling from the command line with `lfec` also generates the error.

Thank you,
den

**Comment by rvirding** [comment]
This is a bug which I will fix real soon now. It has also come up in the slack `#general` channel. There is a quick fix which works in the REPL and the compiler, and is actually fully legal as well 😄 

```
(defun chop
  (((binary ("xyz") (more binary)))
    (io:format "CHOP: ~p~n" `(,more)))

  ((_)                         ;Note the _ here to match all
    'nochop))
```

**Comment by oubiwann** [comment]
Thanks for filing this ticket ... we should have done so when this came up a while back, and again when it came up a few weeks ago :-)

**Comment by dendrown** [comment]
Thank you.  I'm very glad to see there's a nice work-around while waiting on the fix.

@rvirding : thanks also for the note about the underscore.  Somewhere along the line I got the idea that an LFE hyphen was like an Erlang underscore.

**Comment by rvirding** [comment]
This should now work as expected after a commit in develop. I will merge this into master RSN if no one finds any serious errors.

**Comment by dendrown** [comment]
Thanks, Robert.  I verified that this fixes the toy example.  I'm still having a problem in the actual project.

Yet, this may now likely be a rebar3_lfe plugin issue.  Even though I've deleted lfe from the plugin's cache and then watched it pull & rebuild the updated  lfe develop branch, I'm still getting the error.  However, if I call lfec from the plugin's cache to compile the module individually, I get no error.  Also, if I compile the module from the repl, there's no error.

Note that the project still builds fine when I have the work-around you mentioned in place.  So, I'm not stopped.at all.  In fact, a couple of weeks ago I rewrote that module in Erlang, so I could move forward.  Now, I've reinstated the LFE version in the project.

**Comment by rvirding** [comment]
@dendrown do you still have this problem? If so could you give me an example of how it happens?

**Comment by dendrown** [comment]
Hi @rvirding .  I just went back and took out the work-around in the larger project, and things look good.  The code compiles and works as expected.  I'm on LFE v2.0.1.

Just note that I'm still using rebar v3.14.1, and I haven't dared to upgrade since I found the lfe_rebar3#68  issue I referenced above.

**Comment by oubiwann** [comment]
Closing since the fix is now merged ...

(@dendrown btw, that rebar3_lfe bug is now fixed 😄)

**Comment by dendrown** [comment]
Thanks @rvirding and @oubiwann !!
